// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: DomainLayer/response_enum.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseEnum int32

const (
	ResponseEnum_GOOD       ResponseEnum = 0
	ResponseEnum_ERROR      ResponseEnum = 1
	ResponseEnum_BAD_DETAIL ResponseEnum = 2
	ResponseEnum_NOT_FOUND  ResponseEnum = 3
)

// Enum value maps for ResponseEnum.
var (
	ResponseEnum_name = map[int32]string{
		0: "GOOD",
		1: "ERROR",
		2: "BAD_DETAIL",
		3: "NOT_FOUND",
	}
	ResponseEnum_value = map[string]int32{
		"GOOD":       0,
		"ERROR":      1,
		"BAD_DETAIL": 2,
		"NOT_FOUND":  3,
	}
)

func (x ResponseEnum) Enum() *ResponseEnum {
	p := new(ResponseEnum)
	*p = x
	return p
}

func (x ResponseEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_DomainLayer_response_enum_proto_enumTypes[0].Descriptor()
}

func (ResponseEnum) Type() protoreflect.EnumType {
	return &file_DomainLayer_response_enum_proto_enumTypes[0]
}

func (x ResponseEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseEnum.Descriptor instead.
func (ResponseEnum) EnumDescriptor() ([]byte, []int) {
	return file_DomainLayer_response_enum_proto_rawDescGZIP(), []int{0}
}

var File_DomainLayer_response_enum_proto protoreflect.FileDescriptor

var file_DomainLayer_response_enum_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x2a, 0x42, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f, 0x4f, 0x44, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x42, 0x41, 0x44, 0x5f, 0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x03, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_DomainLayer_response_enum_proto_rawDescOnce sync.Once
	file_DomainLayer_response_enum_proto_rawDescData []byte
)

func file_DomainLayer_response_enum_proto_rawDescGZIP() []byte {
	file_DomainLayer_response_enum_proto_rawDescOnce.Do(func() {
		file_DomainLayer_response_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DomainLayer_response_enum_proto_rawDesc), len(file_DomainLayer_response_enum_proto_rawDesc)))
	})
	return file_DomainLayer_response_enum_proto_rawDescData
}

var file_DomainLayer_response_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DomainLayer_response_enum_proto_goTypes = []any{
	(ResponseEnum)(0), // 0: grpc.ResponseEnum
}
var file_DomainLayer_response_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DomainLayer_response_enum_proto_init() }
func file_DomainLayer_response_enum_proto_init() {
	if File_DomainLayer_response_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DomainLayer_response_enum_proto_rawDesc), len(file_DomainLayer_response_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DomainLayer_response_enum_proto_goTypes,
		DependencyIndexes: file_DomainLayer_response_enum_proto_depIdxs,
		EnumInfos:         file_DomainLayer_response_enum_proto_enumTypes,
	}.Build()
	File_DomainLayer_response_enum_proto = out.File
	file_DomainLayer_response_enum_proto_goTypes = nil
	file_DomainLayer_response_enum_proto_depIdxs = nil
}
