// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: DomainLayer/stream_message_enum.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamMessageEnum int32

const (
	StreamMessageEnum_RUN_TASK    StreamMessageEnum = 0 //要求子节点运行任务
	StreamMessageEnum_CANCEL_TASK StreamMessageEnum = 1 //要求子节点取消任务
	StreamMessageEnum_CREATE_DATA StreamMessageEnum = 2 //增加某些数据
	StreamMessageEnum_CREATE_LOGS StreamMessageEnum = 3 //增加日志
	StreamMessageEnum_CONNECT     StreamMessageEnum = 4
	StreamMessageEnum_DISCONNECT  StreamMessageEnum = 5
	StreamMessageEnum_SEND        StreamMessageEnum = 6
	StreamMessageEnum_PING        StreamMessageEnum = 7 //心跳战术的一部分
)

// Enum value maps for StreamMessageEnum.
var (
	StreamMessageEnum_name = map[int32]string{
		0: "RUN_TASK",
		1: "CANCEL_TASK",
		2: "CREATE_DATA",
		3: "CREATE_LOGS",
		4: "CONNECT",
		5: "DISCONNECT",
		6: "SEND",
		7: "PING",
	}
	StreamMessageEnum_value = map[string]int32{
		"RUN_TASK":    0,
		"CANCEL_TASK": 1,
		"CREATE_DATA": 2,
		"CREATE_LOGS": 3,
		"CONNECT":     4,
		"DISCONNECT":  5,
		"SEND":        6,
		"PING":        7,
	}
)

func (x StreamMessageEnum) Enum() *StreamMessageEnum {
	p := new(StreamMessageEnum)
	*p = x
	return p
}

func (x StreamMessageEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMessageEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_DomainLayer_stream_message_enum_proto_enumTypes[0].Descriptor()
}

func (StreamMessageEnum) Type() protoreflect.EnumType {
	return &file_DomainLayer_stream_message_enum_proto_enumTypes[0]
}

func (x StreamMessageEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMessageEnum.Descriptor instead.
func (StreamMessageEnum) EnumDescriptor() ([]byte, []int) {
	return file_DomainLayer_stream_message_enum_proto_rawDescGZIP(), []int{0}
}

var File_DomainLayer_stream_message_enum_proto protoreflect.FileDescriptor

var file_DomainLayer_stream_message_enum_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x75,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x2a, 0x85, 0x01,
	0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x55, 0x4e, 0x5f, 0x54, 0x41, 0x53, 0x4b, 0x10,
	0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x54, 0x41, 0x53, 0x4b,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x44, 0x41, 0x54,
	0x41, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f,
	0x47, 0x53, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10,
	0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10,
	0x05, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x45, 0x4e, 0x44, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x49, 0x4e, 0x47, 0x10, 0x07, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_DomainLayer_stream_message_enum_proto_rawDescOnce sync.Once
	file_DomainLayer_stream_message_enum_proto_rawDescData []byte
)

func file_DomainLayer_stream_message_enum_proto_rawDescGZIP() []byte {
	file_DomainLayer_stream_message_enum_proto_rawDescOnce.Do(func() {
		file_DomainLayer_stream_message_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_DomainLayer_stream_message_enum_proto_rawDesc), len(file_DomainLayer_stream_message_enum_proto_rawDesc)))
	})
	return file_DomainLayer_stream_message_enum_proto_rawDescData
}

var file_DomainLayer_stream_message_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_DomainLayer_stream_message_enum_proto_goTypes = []any{
	(StreamMessageEnum)(0), // 0: grpc.StreamMessageEnum
}
var file_DomainLayer_stream_message_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_DomainLayer_stream_message_enum_proto_init() }
func file_DomainLayer_stream_message_enum_proto_init() {
	if File_DomainLayer_stream_message_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_DomainLayer_stream_message_enum_proto_rawDesc), len(file_DomainLayer_stream_message_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_DomainLayer_stream_message_enum_proto_goTypes,
		DependencyIndexes: file_DomainLayer_stream_message_enum_proto_depIdxs,
		EnumInfos:         file_DomainLayer_stream_message_enum_proto_enumTypes,
	}.Build()
	File_DomainLayer_stream_message_enum_proto = out.File
	file_DomainLayer_stream_message_enum_proto_goTypes = nil
	file_DomainLayer_stream_message_enum_proto_depIdxs = nil
}
